name: Apply Terraform changes on merge

on:
  push:
    branches:
      - main  # or any other branch you want to trigger the deployment
    paths: 
      - '**/*.tf'

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2 

    - name: Terraform Apply
      uses: dflook/terraform-apply@v1
      with:
        path: terraform
        backend_config_file: terraform/prod.backend.tfvars
